language: ruby
rvm:
  - 1.9.3
  - 2.0.0
before_install:
  - gem install bundler
before_script:
  - bundle --version
  - cp config/database.ci.yml config/database.yml
  - psql -c 'create database billing_test;' -U postgres
  - bundle exec rake db:migrate
script:
  - bundle exec rspec spec/ --backtrace --color
branches:
  only:
    - master
notifications:
  email: false
  campfire:
    on_success: change
    on_failure: always
    rooms:
      - secure: "cyEVlNK8v9s66nIlsdycyGUNFKyRIARy74+oOM9RZ+EQcYL2D/0XMsUyevQx\nLFWMN5Clv1N20zhOYhYbUklPSHuT0hVoSfkMSeNlEFiy2HqIrWO8rFqazJLt\nw4HLCtl0AOc77L/1QgBfoU27g4VaPwAZvoUO6MM071wFaCwAIZA="