language: ruby
rvm:
  - 2.1.2
env:
  global:
    SPEC_OPTS=--backtrace --color
bundler_args: --deployment --without development
cache: bundler
before_install:
  - gem install bundler
  - bundle --version
before_script:
  - cp config/database.ci.yml config/database.yml
  - psql -c 'create database orientation_test;' -U postgres
  - bundle exec rake db:migrate
script:
  - bundle exec rspec spec/ 
branches:
  only:
    - master
notifications:
  email: false
  hipchat:
    on_success: change
    on_failure: always
    rooms:
      - secure: "Vn4UUiuKxZ88o1mjDt7iKX8QBjwZyw9HIs2x0H7F3DDHkAHAnb+TCJAqDuIVTp9rCY2tnHDdkwIWjb2pK8se83PFLwYjeY6SErXGCh1Dvkyr8XU/tBfHz+u90TWzF4H9nFKxRz2bC2BR3u9D1D7hB6iwjy+OWOmcL05LLijDurU="
addons:
  code_climate:
    repo_token: 8439cc8914b3303d4cdf247fab922d07564d14693cdfe9e0c7c37ffaecd6ff53 
