language: ruby
rvm:
  - 1.9.3
  - 2.0.0
script:
  - "RAILS_ENV=test bundle exec rake --trace db:migrate spec"
branches:
  only:
    - master
notifications:
  email: false
  campfire:
    on_success: change
    on_failure: always
    rooms:
      - secure: "cyEVlNK8v9s66nIlsdycyGUNFKyRIARy74+oOM9RZ+EQcYL2D/0XMsUyevQx\nLFWMN5Clv1N20zhOYhYbUklPSHuT0hVoSfkMSeNlEFiy2HqIrWO8rFqazJLt\nw4HLCtl0AOc77L/1QgBfoU27g4VaPwAZvoUO6MM071wFaCwAIZA="