development: &postgres
  adapter: postgresql
  encoding: unicode
  database: <%= Rails.application.secrets[:database][:name] %>
  username: <%= Rails.application.secrets[:database][:username] %>
  password: <%= Rails.application.secrets[:database][:password] %>

test:
  <<: *postgres
  database: orientation_test
