development:
  adapter: postgresql
  encoding: unicode
  database: orientation_development
  pool: 5
  username: olivierlacan
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: orientation_test
  pool: 5
  username: olivierlacan
  password: